name: Run Sniper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - run: pip install requests
      
      - run: python main.py
      
      - name: Commit & Push
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add sub.txt
          # این خط جلوی قرمز شدن را می‌گیرد
          git commit -m "Update" || exit 0
          git push
